name: Build & Push Frontend

on:
  push:
    branches: ["main"]
    tags: ["v*.*.*"]
    paths: ["frontend/**"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: { contents: read, packages: write }

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine image name and tag
        run: |
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_NAME=ghcr.io/${REPO_LOWER}/frontend" >> $GITHUB_ENV
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            echo "TAG=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          else
            echo "TAG=latest" >> $GITHUB_ENV
          fi

      - name: Build
        run: docker build -t "${{ env.IMAGE_NAME }}:${{ env.TAG }}" ./frontend

      - name: Push
        run: docker push "${{ env.IMAGE_NAME }}:${{ env.TAG }}"
